CREATE TABLE llx_c_customstock_type(
    rowid INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    code VARCHAR(10) NOT NULL,
    label VARCHAR(128) NOT NULL,
    active TINYINT(4) NOT NULL DEFAULT 1

) ENGINE=InnoDB DEFAULT CHARSET=utf8;